# compile client and server
all: ftpcli ftpserv

# compile client only
# compile client only
ftpcli:
	javac FtpCli.java

# compile server program
ftpserv:
	javac FtpServ.java

clean:
	rm -f *.class FtpServ FtpCli
